name: indian_gaming_community
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.3+6
  android_intent: ^0.3.2
  webview_flutter: ^0.3.13
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+8
  firebase_admob: ^0.5.5
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/avatar.png
    - images/youtubeIco.png
    - images/discordIcon.png
    - images/banner.jpg
    - images/icons/

  fonts:
    - family: LexendPeta
      fonts:
        - asset: fonts/LexendPeta-Regular.ttf
